In [2]:
import numpy as np


In [5]:

np.__version__, np.__config__






('1.21.5',
 <module 'numpy.__config__' from 'C:\\Users\\new\\anaconda3\\lib\\site-packages\\numpy\\__config__.py'>)

In [7]:
x1=np.array([[2, 3],[4 ,7]])
x1

array([[2, 3],
       [4, 7]])

In [8]:
#memory size
print(x1.nbytes)

16


In [9]:
#Data type
print(x1.dtype)

int32


In [10]:
#null vector with size 10
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
#documentation of numpy add
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [19]:
#Null vector size 10,fifth value=1
x1=np.zeros(10)
x1[4]=1
x1


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [26]:
#Reverse vector
t=np.random.randint(10,size=(3 ,4))
t

array([[2, 3, 8, 9],
       [1, 1, 6, 0],
       [4, 1, 7, 0]])

In [27]:
t[::-1]

array([[4, 1, 7, 0],
       [1, 1, 6, 0],
       [2, 3, 8, 9]])

In [28]:
#vector with values 10-49
v=np.arange(10,49)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [30]:
#3by3 matrix with values ranging from 0-8
z=np.arange(0,8)
z

array([0, 1, 2, 3, 4, 5, 6, 7])

In [36]:
print(z.reshape(4,2))

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [40]:
m=[0,0,1,0,4,6,0,0]
print(m.index(1))
print(m.index(4))
print(m.index(6))


2
4
5


In [41]:
#3by3 identity matrix
u=np.eye(3)
u

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
#3 dimension array(3by3by3)
b=np.random.random((3,3,3))
b

array([[[0.95775486, 0.66815764, 0.22597364],
        [0.77256525, 0.60484467, 0.99334705],
        [0.52853203, 0.36689087, 0.09037877]],

       [[0.5164563 , 0.2415481 , 0.7244516 ],
        [0.49052521, 0.3751514 , 0.27722096],
        [0.76817568, 0.81810693, 0.32294898]],

       [[0.92687563, 0.92843692, 0.821962  ],
        [0.50355019, 0.98772193, 0.37661483],
        [0.73452171, 0.38807596, 0.86514083]]])

In [44]:

#10by1`0 matrix with min() and max()
h=np.random.random((10,10))
h

array([[0.66202033, 0.0746668 , 0.08447493, 0.35601767, 0.51997968,
        0.78504385, 0.43595905, 0.86114816, 0.75712513, 0.93985226],
       [0.24171058, 0.73896731, 0.08037152, 0.45895845, 0.18885235,
        0.10480135, 0.29029482, 0.27233434, 0.32276937, 0.83799198],
       [0.86091784, 0.14019831, 0.98712797, 0.14561995, 0.59749323,
        0.80636752, 0.95765998, 0.7901493 , 0.0521204 , 0.0797928 ],
       [0.63726242, 0.66327417, 0.9158334 , 0.22902096, 0.66396607,
        0.34003573, 0.44329009, 0.32243551, 0.15122703, 0.15425868],
       [0.74275334, 0.06106692, 0.32423151, 0.78726347, 0.29200634,
        0.18349401, 0.17166344, 0.93084143, 0.88547568, 0.39406818],
       [0.56341193, 0.61422126, 0.39744225, 0.69401493, 0.26261132,
        0.07195479, 0.05738883, 0.27017702, 0.60022854, 0.79840398],
       [0.19623125, 0.15806422, 0.1179736 , 0.05750291, 0.58325931,
        0.81477943, 0.55454958, 0.77980653, 0.75013241, 0.22932516],
       [0.00155718, 0.0925964 , 0.1566923

In [47]:
print(h.min())
print(h.max())

0.0015571813397413647
0.9871279671368419


In [48]:
#random vector size 30,find mean
f=np.random.random(30)
f

array([0.07972683, 0.29078206, 0.6723841 , 0.98161049, 0.37761192,
       0.90980524, 0.36074807, 0.60120631, 0.4124147 , 0.27213383,
       0.11389604, 0.85851047, 0.68465033, 0.50785579, 0.76675644,
       0.19993692, 0.0475014 , 0.07546029, 0.556397  , 0.78695313,
       0.38290251, 0.95604147, 0.22152722, 0.7567251 , 0.36191369,
       0.29687988, 0.25106903, 0.48102224, 0.22043709, 0.6400852 ])

In [50]:
print(f.mean())

0.47083149237225214
